# Generated by Django 2.1.5 on 2019-06-05 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filters', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Offer_discription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('photo', models.ImageField(default='/media/off2.jpg', upload_to='images/')),
                ('photo1', models.ImageField(default='/media/off2.jpg', upload_to='images/')),
                ('photo2', models.ImageField(blank=True, upload_to='images/')),
                ('photo3', models.ImageField(blank=True, upload_to='images/')),
                ('photo4', models.ImageField(blank=True, upload_to='images/')),
                ('photo5', models.ImageField(blank=True, upload_to='images/')),
                ('address', models.TextField(max_length=100)),
                ('ready_post', models.BooleanField(default=True)),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='interface.Categories')),
                ('likes', models.ManyToManyField(blank=True, default=0, related_name='post_likes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShopProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=100, unique=True)),
                ('address', models.TextField(max_length=100)),
                ('shop_discription', models.TextField(max_length=250)),
                ('photo1', models.ImageField(upload_to='images/')),
                ('photo2', models.ImageField(blank=True, upload_to='images/')),
                ('photo3', models.ImageField(blank=True, upload_to='images/')),
                ('photo4', models.ImageField(blank=True, upload_to='images/')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=12)),
                ('is_verifieduser', models.BooleanField(default=True)),
                ('is_shopkeeper', models.BooleanField(default=False)),
                ('is_user', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
