# Generated by Django 2.1.5 on 2019-06-27 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0002_offer_discription_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer_discription',
            name='offer_tag',
            field=models.CharField(default='initial', max_length=100),
        ),
    ]
