# Generated by Django 2.1.5 on 2019-08-09 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0004_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='offer_images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='images/')),
            ],
        ),
        migrations.RenameField(
            model_name='offer_discription',
            old_name='photo',
            new_name='index_photo',
        ),
        migrations.RemoveField(
            model_name='offer_discription',
            name='photo1',
        ),
        migrations.RemoveField(
            model_name='offer_discription',
            name='photo2',
        ),
        migrations.RemoveField(
            model_name='offer_discription',
            name='photo3',
        ),
        migrations.RemoveField(
            model_name='offer_discription',
            name='photo4',
        ),
        migrations.RemoveField(
            model_name='offer_discription',
            name='photo5',
        ),
        migrations.AddField(
            model_name='offer_discription',
            name='comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='offer_images',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.Offer_discription'),
        ),
    ]
